<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Mail\LoginVerificationCodeMail;
use App\Models\LoginVerificationCode;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

/**
 * Email + one-time verification code login (replaces password-based
 * login). This is NOT "Sign in with Google" / OAuth — the code is
 * generated by this application and delivered by email; Google/Gmail (or
 * any other provider configured in .env) is only used as the mail
 * transport. Existing Admin/Agent roles and authorization are unchanged —
 * this only replaces how a session gets authenticated in the first place.
 */
class LoginController extends Controller
{
    /** How many codes a given email+IP may request within the decay window. */
    private const MAX_CODE_REQUESTS = 3;

    private const CODE_REQUEST_DECAY_SECONDS = 600;

    /** How many failed verification submissions a given email+IP may make within the decay window. */
    private const MAX_VERIFY_ATTEMPTS = 5;

    private const VERIFY_DECAY_SECONDS = 600;

    /** Step 1: ask for the email address. */
    public function create(): View
    {
        return view('auth.login');
    }

    /** Step 1 submit: validate the email, generate and email a code, move to step 2. */
    public function sendCode(Request $request): RedirectResponse
    {
        $data = $request->validate([
            'email' => ['required', 'string', 'email'],
        ]);

        $email = mb_strtolower(trim($data['email']));

        $throttleKey = $this->codeRequestThrottleKey($request, $email);

        if (RateLimiter::tooManyAttempts($throttleKey, self::MAX_CODE_REQUESTS)) {
            throw ValidationException::withMessages([
                'email' => sprintf(
                    'Demasiadas solicitudes de código. Intenta de nuevo en %d minuto(s).',
                    (int) ceil(RateLimiter::availableIn($throttleKey) / 60)
                ),
            ]);
        }

        RateLimiter::hit($throttleKey, self::CODE_REQUEST_DECAY_SECONDS);

        // The response is identical whether or not the account exists, so
        // this form can't be used to discover which emails have access here.
        // Only known users actually get a code generated and emailed.
        if (User::where('email', $email)->exists()) {
            [, $plainCode] = LoginVerificationCode::generateFor($email);

            Mail::to($email)->send(new LoginVerificationCodeMail($plainCode));
        }

        $request->session()->put('login.pending_email', $email);
        $request->session()->put('login.remember', $request->boolean('remember'));

        return redirect()->route('login.verify')->with('status', 'Si el correo tiene una cuenta, te enviamos un código de verificación.');
    }

    /** Step 2: enter the code. */
    public function showVerify(Request $request): View|RedirectResponse
    {
        if (! $request->session()->has('login.pending_email')) {
            return redirect()->route('login');
        }

        return view('auth.verify-code', [
            'email' => $request->session()->get('login.pending_email'),
        ]);
    }

    /** Step 2 submit: verify the code and authenticate the session. */
    public function verifyCode(Request $request): RedirectResponse
    {
        $email = $request->session()->get('login.pending_email');

        if (! $email) {
            return redirect()->route('login');
        }

        $request->validate([
            'code' => ['required', 'string'],
        ]);

        $throttleKey = $this->verifyThrottleKey($request, $email);

        if (RateLimiter::tooManyAttempts($throttleKey, self::MAX_VERIFY_ATTEMPTS)) {
            throw ValidationException::withMessages([
                'code' => sprintf(
                    'Demasiados intentos. Intenta de nuevo en %d minuto(s) o solicita un nuevo código.',
                    (int) ceil(RateLimiter::availableIn($throttleKey) / 60)
                ),
            ]);
        }

        $codeModel = LoginVerificationCode::activeFor($email);

        if (! $codeModel || $codeModel->isLockedOut()) {
            RateLimiter::hit($throttleKey, self::VERIFY_DECAY_SECONDS);

            throw ValidationException::withMessages([
                'code' => 'El código no es válido o ya expiró. Solicita uno nuevo.',
            ]);
        }

        if (! $codeModel->matches((string) $request->input('code'))) {
            $codeModel->registerFailedAttempt();
            RateLimiter::hit($throttleKey, self::VERIFY_DECAY_SECONDS);

            throw ValidationException::withMessages([
                'code' => 'El código no es válido.',
            ]);
        }

        $user = User::where('email', $email)->first();

        if (! $user) {
            throw ValidationException::withMessages([
                'code' => 'No se encontró una cuenta con ese correo electrónico.',
            ]);
        }

        $codeModel->markConsumed();
        RateLimiter::clear($throttleKey);
        RateLimiter::clear($this->codeRequestThrottleKey($request, $email));

        $remember = (bool) $request->session()->pull('login.remember', false);
        $request->session()->forget('login.pending_email');

        Auth::login($user, $remember);
        $request->session()->regenerate();

        return redirect()->intended(route('dashboard'));
    }

    public function destroy(Request $request): RedirectResponse
    {
        Auth::logout();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('login');
    }

    private function codeRequestThrottleKey(Request $request, string $email): string
    {
        return 'login-code:'.$request->ip().'|'.$email;
    }

    private function verifyThrottleKey(Request $request, string $email): string
    {
        return 'login-verify:'.$request->ip().'|'.$email;
    }
}
